export enum UserStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  SUSPENDED = "SUSPENDED",
}

export enum RoleStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

export enum PermissionAction {
  VIEW = "VIEW",
  CREATE = "CREATE",
  EDIT = "EDIT",
  DELETE = "DELETE",
  APPROVE = "APPROVE",
  REJECT = "REJECT",
  EXPORT = "EXPORT",
  IMPORT = "IMPORT",
  PRINT = "PRINT",
  DOWNLOAD = "DOWNLOAD",
  SHARE = "SHARE",
}

export enum WorkflowInstanceStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
}

export enum ApprovalDecision {
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  ESCALATED = "ESCALATED",
  RESUBMITTED = "RESUBMITTED",
}

export enum BusinessType {
  PROPRIETORSHIP = "PROPRIETORSHIP",
  PARTNERSHIP = "PARTNERSHIP",
  PRIVATE_LIMITED = "PRIVATE_LIMITED",
  LLP = "LLP",
  PUBLIC_LIMITED = "PUBLIC_LIMITED",
  OTHER = "OTHER",
}

export enum BrandApprovalStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum ProductStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  DRAFT = "DRAFT",
}

export enum Region {
  PAN_INDIA = "PAN_INDIA",
  NORTH_INDIA = "NORTH_INDIA",
  SOUTH_INDIA = "SOUTH_INDIA",
  EAST_INDIA = "EAST_INDIA",
  WEST_INDIA = "WEST_INDIA",
  KERALA = "KERALA",
}

export enum ArtworkSubmissionType {
  REFERENCE = "REFERENCE",
  READY_ARTWORK = "READY_ARTWORK",
}

export enum ArtworkFileType {
  REFERENCE = "REFERENCE",
  CREATIVE_ARTWORK = "CREATIVE_ARTWORK",
  READY_ARTWORK = "READY_ARTWORK",
}

export enum OrderStatus {
  PLACED = "PLACED",
  DELIVERED = "DELIVERED",
  CREATIVE_IN_PROGRESS = "CREATIVE_IN_PROGRESS",
  PENDING_BRAND_APPROVAL = "PENDING_BRAND_APPROVAL",
  ARTWORK_REJECTED = "ARTWORK_REJECTED",
  ARTWORK_APPROVED = "ARTWORK_APPROVED",
  PENDING_VENDOR_ASSIGNMENT = "PENDING_VENDOR_ASSIGNMENT",
  VENDOR_ASSIGNED = "VENDOR_ASSIGNED",
  IN_PRODUCTION = "IN_PRODUCTION",
  INSTALLATION_COMPLETE = "INSTALLATION_COMPLETE",
  PAYMENT_PENDING = "PAYMENT_PENDING",
  PAYMENT_RECEIVED = "PAYMENT_RECEIVED",
  CANCELLED = "CANCELLED",
}

export enum VendorApprovalStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum NegotiationStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
}

export enum InvoiceStatus {
  DRAFT = "DRAFT",
  ISSUED = "ISSUED",
  PAID = "PAID",
  OVERDUE = "OVERDUE",
}

export enum AlertType {
  SLA_BREACH = "SLA_BREACH",
  NEGOTIATION_STUCK = "NEGOTIATION_STUCK",
  APPROVAL_OVERDUE = "APPROVAL_OVERDUE",
  OTHER = "OTHER",
}

export enum AlertSeverity {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
}

export enum LogLevel {
  INFO = "INFO",
  WARNING = "WARNING",
  ERROR = "ERROR",
  CRITICAL = "CRITICAL",
}

export enum BackupStatus {
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
  IN_PROGRESS = "IN_PROGRESS",
}

export enum SubscriptionStatus {
  ACTIVE = "ACTIVE",
  EXPIRED = "EXPIRED",
  SUSPENDED = "SUSPENDED",
}

export enum ActorType {
  INTERNAL_USER = "INTERNAL_USER",
  BRAND = "BRAND",
  VENDOR = "VENDOR",
  SYSTEM = "SYSTEM",
}

export enum AuditAction {
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  FAILED_LOGIN = "FAILED_LOGIN",
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  APPROVE = "APPROVE",
  REJECT = "REJECT",
  STATUS_CHANGE = "STATUS_CHANGE",
  FILE_UPLOAD = "FILE_UPLOAD",
  FILE_DOWNLOAD = "FILE_DOWNLOAD",
  DATA_EXPORT = "DATA_EXPORT",
  PASSWORD_CHANGE = "PASSWORD_CHANGE",
  PERMISSION_CHANGE = "PERMISSION_CHANGE",
  SECURITY_EVENT = "SECURITY_EVENT",
}

export enum NotificationRecipientType {
  INTERNAL_USER = "INTERNAL_USER",
  BRAND = "BRAND",
  VENDOR = "VENDOR",
}

export enum BusinessModelType {
  VENDOR_MODEL = "VENDOR_MODEL",
  MEDIATOR_MODEL = "MEDIATOR_MODEL",
  HYBRID_MODEL = "HYBRID_MODEL",
}
